spring:
  application:
    name: lemon-app

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus

mqtt:
  broker-uri: tcp://${IP}:1883
  topic-sensor-data: esp32/dht/sensor/data
  topic-sensor-anomalies: esp32/dht/sensor/anomalies
  client-id: ${CLIENT_ID:lemon-app-client}
  qos: ${QOS:1}

gcp:
  project-id: ${GCP_PROJECT_ID:lemon-app}
  instance-id: ${GCP_INSTANCE_ID:lemon-table}
  table-id: ${GCP_TABLE_ID:dht-sensor}
  column-family-temp-c: ${GCP_COLUMN_FAMILY:temp_c}
  column-family-hum: ${GCP_COLUMN_FAMILY:hum}

sliding-window:
  window-size: ${SLIDING_WINDOW_SIZE:10}
  sigma: ${SLIDING_WINDOW_SIGMA:2.0}
  min-bounds: ${SLIDING_WINDOW_MIN_BOUNDS:1.0}
